<?php
// $Id$

/**
 * @file
 * A module exemplifying Drupal coding practices and APIs.
 *
 * This module provides a block that lists all of the
 * installed modules. It illustrates coding standards,
 * practices, and API use for Drupal 7.
 */

/**
 * Implements hook_help().
 */
function mtt_twitter_help($path, $arg) {
  if ($path == 'admin/help#mtt_twitter') {
    return t('The MtT Twitter module creates a block that gets and displays feeds from a specified twitter account. As soon as you enable the module you will find an extra block available in your list of blocks. Configure this block to set your preferred twitter account and interval time.');
  }
}

/**
 * Implements hook_block_info().
 */
function mtt_twitter_block_info() {
  $blocks = array();

  $blocks['latest_tweets'] = array(
    'info' => t('MtT Twitter'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function mtt_twitter_block_view($block_name = '') {
  drupal_add_js('http://widgets.twimg.com/j/2/widget.js', 'external');
  if ($block_name == 'latest_tweets') {
  	$account=variable_get('mtt_twitter_account');
	$interval=variable_get('mtt_twitter_interval')*1000;
	$title=variable_get('mtt_twitter_title');
    $content = "<div class='twitter-title'>$title</div>
				<script type='text/javascript'>
				new TWTR.Widget({
				  version: 2,
				  type: 'search',
				  search: '$account',
				  interval: '$interval',
				  title: '',
				  subject: '',
				  width: 'auto',
				  theme: {
					shell: {
					  background: 'transparent',
					  color: '#ffffff'
					},
					tweets: {
					  background: 'transparent',
					  color: '#ffffff',
					  links: '#b8e2f6'
					}
				  },
				  features: {
					scrollbar: false,
					loop: true,
					live: true,
					hashtags: true,
					timestamp: false,
					avatars: false,
					toptweets: false,
					behavior: 'default'
				  }
				}).render().start();
				</script>
				";
	
    $block = array(
      'subject' => t(''),
      'content' => $content,
    );

    return $block;
  }
}

function mtt_twitter_admin() {
  $form = array();

  $form['mtt_twitter_account'] = array(
    '#type' => 'textfield',
    '#title' => t('Twitter account'),
    '#default_value' => variable_get('mtt_twitter_account', 'morethanthemes'),
    '#size' => 64,
    '#description' => t("Enter the twitter account you want to display feeds from."),
    '#required' => TRUE,
  );
  
  $form['mtt_twitter_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Twitter title'),
    '#default_value' => variable_get('mtt_twitter_title', 'Latest updates from Twitter'),
    '#size' => 64,
    '#description' => t("Enter the twitter title you want to display."),
    '#required' => TRUE,
  );
  
  $form['mtt_twitter_interval'] = array(
    '#type' => 'textfield',
    '#title' => t('Time interval'),
    '#default_value' => variable_get('mtt_twitter_interval', '5'),
    '#size' => 64,
    '#description' => t("Set the time interval between twitter posts, in seconds."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function mtt_twitter_menu() {

  $items = array();

  $items['admin/config/system/mtt_twitter'] = array(
    'title' => 'MtT Twitter',
    'description' => 'MtT Twitter configuration page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mtt_twitter_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

?>